sudo: required
os:
  - linux
dist: xenial
language: c++

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - g++

install: 
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq build-essential cmake cpp gcc clang libsensors4-dev libboost-filesystem-dev libboost-system-dev libpthread-stubs0-dev libexplain-dev

compiler:
  - g++
  - clang++

before_script:
  - cmake .

script:
  - make

notifications:
  email:
    - haydenbriese@gmail.com

on_success: change
on_failure: always


