notifications: # set notification options
  email:
    recipients:
      - haydenbriese@gmail.com

# change is when the repo status goes from pass to fail or vice versa
on_success: change
on_failure: always

sudo: required
dist: xenial

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - gcc
      - g++

install: 
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake gcc clang libsensors4 libboost-filesystem-dev libboost-system-dev libpthread-stubs0-dev

matrix:
  include:
    - env: CXX=g++ CC=gcc
    - env: CXX=clang++ CC=clang

language: cpp
compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
