sudo: required
os:
  - linux
dist: xenial

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - gcc
      - g++

install: 
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake gcc clang libsensors4-dev libboost-filesystem-dev libboost-system-dev libpthread-stubs0-dev libexplain-dev

matrix:
  include:
    - env: CXX=g++ CC=gcc
    - env: CXX=clang++ CC=clang
    - env: CXXFLAGS="--std=c++14"

language: cpp
compiler:
  - gcc
  - clang

before_script:
  - cmake .

script:
  - make

notifications:
  email:
    - haydenbriese@gmail.com

on_success: change
on_failure: always


